services:
  backend:
    container_name: backend-opti
    build:
      context: backend
      dockerfile: Dockerfile.pub
    image: arahnaaurum/backend-opti:1.0.0
    env_file: .env
    ports:
      - '4000:3000'
    depends_on:
      - postgres
    restart: always
  frontend:
    container_name: frontend-opti
    build:
      context: frontend
      dockerfile: Dockerfile.pub
    image: arahnaaurum/frontend-opti:1.0.0
    env_file: .env
    ports:
      - '8081:3000'
    restart: always
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file: .env
    restart: always